#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 SuperNovae Studio <contact@supernovae.studio>
"""selftest.py — prove the estate tool is DISCRIMINATING, not merely quiet.

A gate that returns 0 on a clean tree has proven nothing: so does `true`.
What has to be proven is that it returns NON-zero on each thing it claims to
catch, with the exit code it documents. So this builds a throwaway repository,
plants one known violation at a time, and asserts the verdict.

Every case below was found by hand on a real repo first; this file is that
session made repeatable. It is dependency-free and touches nothing outside a
temporary directory.

    python3 scripts/selftest.py          # run the battery
    python3 scripts/selftest.py -v       # show each command's output

    exit 0  every case behaved as documented
    exit 1  at least one case did not  (the tool changed, or regressed)

The battery is also the tool's own regression suite: change estate.py and run
this before pushing. If a case stops firing, the change removed a guarantee.
"""

import os
import pathlib
import shutil
import subprocess
import sys
import tempfile

HERE = pathlib.Path(__file__).resolve().parent
TOOL = HERE / "estate.py"
VERBOSE = "-v" in sys.argv or "--verbose" in sys.argv

PASS, FAIL = "\033[32m✓\033[0m", "\033[31m✗\033[0m"
if not sys.stdout.isatty() or os.environ.get("NO_COLOR"):
    PASS, FAIL = "PASS", "FAIL"


# ── the fixture ─────────────────────────────────────────────────────────────

RULES = '''\
FILES = [
    {"path": SELF, "class": "pinned-copy",
     "evidence": "the shared tool, mirrored",
     "derivation": {"tool": "curl", "gate": "the mirror job", "inputs": ["ESTATE_PIN"]}},
    {"path": RULES, "class": "authored", "evidence": "the per-repo rules"},
    {"path": "ESTATE_PIN", "class": "authored-pin", "evidence": "bump deliberately"},
    {"path": "LICENSE", "class": "pinned-copy", "evidence": "verbatim upstream text",
     "derivation": {"tool": "hand-placed", "gate": "NONE", "inputs": ["upstream"]}},
]

import pathlib as _p
# Evidence-driven: `generated` fires only when the marker is really there.
for _f in ("snippets/projected.md",):
    _head = ""
    try:
        _head = "\\n".join((ROOT / _f).read_text().splitlines()[:4])
    except OSError:
        pass
    if "AUTO-GENERATED by" in _head:
        FILES.append({"path": _f, "class": "generated",
                      "evidence": "in-file marker: AUTO-GENERATED by",
                      "derivation": {"tool": "the projector", "gate": "the parity step",
                                     "inputs": ["upstream source"]}})
    else:
        FILES.append({"path": _f, "class": "authored",
                      "evidence": "expected an AUTO-GENERATED marker and found none",
                      "note": "unverified-default"})

PATTERNS = [
    {"glob": "docs/**.md", "class": "authored", "evidence": "hand-written page"},
    {"glob": "**", "class": "authored", "evidence": "no marker or known role found",
     "note": "unverified-default"},
]
'''

FIXTURE = {
    "README.md": "# fixture\n",
    "LICENSE": "Upstream license text, verbatim.\n",
    "ESTATE_PIN": "# Bump deliberately: edit this\ndeadbeefdeadbeefdeadbeefdeadbeefdeadbeef\n",
    "docs/guide.md": "a page\n",
    "docs/nested/deep.md": "a nested page\n",
    "snippets/projected.md": "<!-- AUTO-GENERATED by the projector -->\nbody\n",
}


def sh(*args, cwd, check=False):
    r = subprocess.run(args, cwd=cwd, capture_output=True, text=True)
    if check and r.returncode:
        raise RuntimeError(f"{args} failed: {r.stderr}")
    return r


def build(root: pathlib.Path):
    """A minimal repo that exercises FILES, PATTERNS, and every class."""
    (root / "scripts").mkdir(parents=True)
    (root / "docs/nested").mkdir(parents=True)
    (root / "snippets").mkdir(parents=True)
    for rel, body in FIXTURE.items():
        (root / rel).write_text(body)
    (root / "scripts/estate_rules.py").write_text(RULES)
    shutil.copy(TOOL, root / "scripts/estate.py")

    sh("git", "init", "-q", "-b", "main", cwd=root, check=True)
    sh("git", "config", "user.email", "selftest@example.invalid", cwd=root, check=True)
    sh("git", "config", "user.name", "selftest", cwd=root, check=True)
    # The tool derives the repo slug from origin and refuses without one.
    sh("git", "remote", "add", "origin",
       "https://github.com/supernovae-st/fixture.git", cwd=root, check=True)
    sh("git", "add", "-A", cwd=root, check=True)
    sh("git", "commit", "-qm", "fixture", cwd=root, check=True)
    r = sh(sys.executable, "scripts/estate.py", "--write", cwd=root)
    if r.returncode:
        raise RuntimeError(f"fixture does not generate: {r.stderr}")
    sh("git", "add", "-A", cwd=root, check=True)
    sh("git", "commit", "-qm", "manifest", cwd=root, check=True)


def check(root, mode="--check"):
    r = sh(sys.executable, "scripts/estate.py", mode, cwd=root)
    if VERBOSE and (r.stdout or r.stderr):
        for line in (r.stdout + r.stderr).strip().split("\n")[:4]:
            print(f"        │ {line}")
    return r.returncode, r.stdout + r.stderr


def reset(root):
    sh("git", "reset", "-q", "--hard", "HEAD", cwd=root)
    sh("git", "clean", "-qfdx", cwd=root)


# ── the battery · one known violation each ──────────────────────────────────

def t_clean(root):
    """a tree nobody touched is in phase"""
    return check(root)[0], 0


def t_content_edit(root):
    """editing a declared file's bytes is drift"""
    (root / "README.md").write_text("# fixture\nand one more line\n")
    sh("git", "add", "-A", cwd=root)
    return check(root)[0], 5


def t_new_file(root):
    """a file nobody declared moves the counts"""
    (root / "docs/smuggled.md").write_text("snuck in\n")
    sh("git", "add", "-A", cwd=root)
    return check(root)[0], 5


def t_coverage_hole(root):
    """with no catch-all, an unmatched file is a HOLE, not a shrug"""
    p = root / "scripts/estate_rules.py"
    t = p.read_text()
    i = t.index('    {"glob": "**", "class": "authored"')
    p.write_text(t[:i] + "]\n")
    (root / "weird.dat").write_text("binary-ish\n")
    sh("git", "add", "-A", cwd=root)
    rc, out = check(root)
    if "COVERAGE HOLE" not in out or "weird.dat" not in out:
        return -1, 3          # it must NAME the offender, not just complain
    return rc, 3


def t_class_outside_law(root):
    """the six classes are the law; a seventh is refused"""
    p = root / "scripts/estate_rules.py"
    p.write_text(p.read_text().replace('"class": "authored", "evidence": "hand-written page"',
                                       '"class": "probably-fine", "evidence": "hand-written page"', 1))
    return check(root)[0], 3


def t_rules_missing(root):
    """no rules must refuse, never silently declare an empty estate"""
    (root / "scripts/estate_rules.py").unlink()
    return check(root)[0], 3


def t_manifest_lies(root):
    """THE case: a hand-edited manifest cannot outlive a re-emission"""
    p = root / "estate.yaml"
    t = p.read_text()
    i = t.index('- path: "snippets/projected.md"')
    j = t.index("class:", i)
    p.write_text(t[:j] + "class: authored" + t[t.index("\n", j):])
    return check(root)[0], 5


def t_evidence_vanishes(root):
    """a projection claim does not outlive the marker that proved it"""
    p = root / "snippets/projected.md"
    p.write_text(p.read_text().replace("AUTO-GENERATED by", "hand-crafted by"))
    sh("git", "add", "-A", cwd=root)
    check(root, "--write")
    body = (root / "estate.yaml").read_text()
    i = body.index('- path: "snippets/projected.md"')
    row = body[i:i + 400]
    ok = "class: authored" in row and "found none" in row
    return (0 if ok else -1), 0


def t_duplicate_files_row(root):
    """the same path declared twice is a rules bug, caught before rendering"""
    p = root / "scripts/estate_rules.py"
    p.write_text(p.read_text().replace(
        'FILES = [\n',
        'FILES = [\n    {"path": "LICENSE", "class": "authored", "evidence": "dupe"},\n', 1))
    return check(root)[0], 3


def t_stale_files_row(root):
    """a files: row pointing at nothing is stale, and says so"""
    p = root / "scripts/estate_rules.py"
    p.write_text(p.read_text().replace(
        'FILES = [\n',
        'FILES = [\n    {"path": "GONE.md", "class": "authored", "evidence": "not here"},\n', 1))
    rc, out = check(root)
    return (rc if "stale" in out.lower() else -1), 3


CASES = [
    ("clean tree in phase", t_clean),
    ("content edit is drift", t_content_edit),
    ("undeclared new file is drift", t_new_file),
    ("uncovered file is a named hole", t_coverage_hole),
    ("class outside the law refused", t_class_outside_law),
    ("missing rules refused", t_rules_missing),
    ("hand-edited manifest cannot lie", t_manifest_lies),
    ("claim dies with its evidence", t_evidence_vanishes),
    ("duplicate files: row refused", t_duplicate_files_row),
    ("stale files: row refused", t_stale_files_row),
]


def main() -> int:
    if not TOOL.is_file():
        print(f"selftest: {TOOL} not found", file=sys.stderr)
        return 1
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="estate-selftest-"))
    root = tmp / "repo"
    failures = []
    try:
        build(root)
        print(f"estate selftest · {len(CASES)} cases · fixture at {root}\n"
              if VERBOSE else f"estate selftest · {len(CASES)} cases\n")
        for name, fn in CASES:
            reset(root)
            got, want = fn(root)
            ok = got == want
            print(f"  {PASS if ok else FAIL}  {name:38s} exit {got}"
                  + ("" if ok else f"  (expected {want})"))
            if not ok:
                failures.append(name)
    finally:
        shutil.rmtree(tmp, ignore_errors=True)

    print()
    if failures:
        print(f"✗ {len(failures)} of {len(CASES)} cases did not behave as documented:")
        for f in failures:
            print(f"    - {f}")
        print("\n  A case that stops firing means a guarantee was removed.")
        return 1
    print(f"✓ {len(CASES)}/{len(CASES)} · the gate refuses everything it claims to refuse")
    return 0


if __name__ == "__main__":
    sys.exit(main())
